SET IMPLICIT_TRANSACTIONS ON; CREATE TABLE T1 (i int PRIMARY KEY);SELECT @@TRANCOUNT AS [Transaction Count];INSERT INTO T1 VALUES(5);
GO
SELECT @@TRANCOUNT AS [Transaction Count];ROLLBACK TRAN
GO
SELECT @@TRANCOUNT AS [Transaction Count];SELECT * FROM T1;SET IMPLICIT_TRANSACTIONS OFF;